Topology
string Topology::id
vector<Component* > Topology::components
void Topology::_deleteAllComponents()
Topology::Topology(const Topology &other)
Topology::Topology(string id, vector< Component * > components)
References setComponents, setID.
Topology Topology::operator=(const Topology &other)
bool Topology::operator==(const Topology &other) const
Component * Topology::getComponent(string id) const
Referenced by getComponentsWithNetlistNode.
void Topology::addComponent(Component *component)
References Component::getID.
void Topology::setComponents(vector< Component * > components)
Referenced by Topology.
void Topology::setID(string id)
Referenced by Topology.
string Topology::getID() const
Referenced by JSON::writeTopology.
vector< Component * > Topology::getComponents() const
Referenced by API::queryDevices.
vector< Component * > Topology::getComponentsWithNetlistNode(string netlistNodeID) const
References Component::connectedTo, getComponent.
Referenced by API::queryDevicesWithNetlistNodes.
void Topology::printComponents() const
Topology::~Topology()