Component
string Component::id
Referenced by _copyComponentValues, getID, setID.
double Component::defaultValue
Referenced by _copyComponentValues, getDefaultValue, operator==, CurrentSource::printComponentInfo, NMOS::printComponentInfo, PMOS::printComponentInfo, Resistor::printComponentInfo, VoltageSource::printComponentInfo, setComponentValues, setDefaultValue, setMinValue.
double Component::minValue
Referenced by _copyComponentValues, getMinValue, operator==, setComponentValues, setDefaultValue, setMaxValue, setMinValue.
double Component::maxValue
Referenced by _copyComponentValues, getMaxValue, operator==, setComponentValues, setDefaultValue, setMaxValue.
map<string , string> Component::netlist
Referenced by _copyComponentValues, ThreeTerminal::getDrain, ThreeTerminal::getGate, getNetlist, ThreeTerminal::getSource, TwoTerminal::getT1, TwoTerminal::getT2, operator==, ThreeTerminal::setNetlist, TwoTerminal::setNetlist, setSingleNetlistTerminal, ThreeTerminal::ThreeTerminal, TwoTerminal::TwoTerminal, ThreeTerminal::validNetlist, TwoTerminal::validNetlist.
virtual bool Component::validNetlist(map< string, string > &)=0
virtual void Component::setNetlist(map< string, string > &)=0
bool Component::validComponentValues(map< string, double > &componentInfo)
Referenced by setComponentValues.
void Component::setSingleNetlistTerminal(string terminal, string value)
References netlist.
Referenced by ThreeTerminal::setDrain, ThreeTerminal::setGate, ThreeTerminal::setSource, TwoTerminal::setT1, TwoTerminal::setT2.
void Component::_copyComponentValues(const Component &other)
References defaultValue, id, maxValue, minValue, netlist.
Referenced by Component, CurrentSource::operator=, NMOS::operator=, PMOS::operator=, Resistor::operator=, VoltageSource::operator=.
Component::Component(const Component &other)
References _copyComponentValues.
Component::Component(string id, map< string, double > &componentValues)
References setComponentValues, setID.
bool Component::operator==(const Component &other) const
References defaultValue, getType, maxValue, minValue, netlist.
void Component::setComponentValues(map< string, double > &)
References defaultValue, maxValue, minValue, validComponentValues.
Referenced by Component.
virtual string Component::getType() const =0
Referenced by operator==.
void Component::setID(string id)
References id.
Referenced by Component.
string Component::getID() const
References id.
Referenced by Topology::addComponent, ThreeTerminal::connectedTo, TwoTerminal::connectedTo.
void Component::setMaxValue(double val)
References maxValue, minValue.
double Component::getMaxValue() const
References maxValue.
void Component::setMinValue(double val)
References defaultValue, minValue.
double Component::getMinValue() const
References minValue.
void Component::setDefaultValue(double val)
References defaultValue, maxValue, minValue.
double Component::getDefaultValue() const
References defaultValue.
virtual void Component::printComponentInfo() const =0
map< string, string > Component::getNetlist() const
References netlist.
virtual bool Component::connectedTo(Component *component) const =0
Referenced by Topology::getComponentsWithNetlistNode.