TwoTerminal
bool TwoTerminal::validNetlist(map< string, string > &netlist)
References Component::netlist.
Referenced by setNetlist.
void TwoTerminal::setNetlist(map< string, string > &netlist)
References Component::netlist, validNetlist.
Referenced by TwoTerminal.
TwoTerminal::TwoTerminal(const TwoTerminal &other)
TwoTerminal::TwoTerminal(string id, map< string, string > &netlist, map< string, double > &info)
References Component::netlist, setNetlist.
void TwoTerminal::setT1(string terminal)
References Component::setSingleNetlistTerminal.
void TwoTerminal::setT2(string terminal)
References Component::setSingleNetlistTerminal.
bool TwoTerminal::connectedTo(Component *component) const
References Component::getID, getT1, getT2.
string TwoTerminal::getT1() const
References Component::netlist.
Referenced by connectedTo, CurrentSource::printComponentInfo, Resistor::printComponentInfo, VoltageSource::printComponentInfo.
string TwoTerminal::getT2() const
References Component::netlist.
Referenced by connectedTo, CurrentSource::printComponentInfo, Resistor::printComponentInfo, VoltageSource::printComponentInfo.
virtual void TwoTerminal::printComponentInfo() const =0