ThreeTerminal
bool ThreeTerminal::validNetlist(map< string, string > &netlist)
References Component::netlist.
Referenced by setNetlist.
void ThreeTerminal::setNetlist(map< string, string > &netlist)
References Component::netlist, validNetlist.
Referenced by ThreeTerminal.
ThreeTerminal::ThreeTerminal(const ThreeTerminal &other)
ThreeTerminal::ThreeTerminal(string id, map< string, string > &netlist, map< string, double > &info)
References Component::netlist, setNetlist.
bool ThreeTerminal::connectedTo(Component *component) const
References getDrain, getGate, Component::getID, getSource.
void ThreeTerminal::setDrain(string terminal)
References Component::setSingleNetlistTerminal.
void ThreeTerminal::setGate(string terminal)
References Component::setSingleNetlistTerminal.
void ThreeTerminal::setSource(string terminal)
References Component::setSingleNetlistTerminal.
string ThreeTerminal::getDrain() const
References Component::netlist.
Referenced by connectedTo, NMOS::printComponentInfo, PMOS::printComponentInfo.
string ThreeTerminal::getGate() const
References Component::netlist.
Referenced by connectedTo, NMOS::printComponentInfo, PMOS::printComponentInfo.
string ThreeTerminal::getSource() const
References Component::netlist.
Referenced by connectedTo, NMOS::printComponentInfo, PMOS::printComponentInfo.
virtual void ThreeTerminal::printComponentInfo() const =0