JSON
Topology * JSON::_createTopology(json parser)
vector< Component * > JSON::_createComponents(json componentsParser)
Component * JSON::_createComponent(json componentParser)
Component * JSON::_createResistor(json componentParser)
Component * JSON::_createNMOS(json componentParser)
json JSON::_writeTopologyComponents(Topology *)
json JSON::_writeTopologyComponent(Component *)
json JSON::_getTopologyInfo(Component *)
JSON::JSON()
Referenced by operator=.
JSON::JSON(const JSON &other)
JSON JSON::operator=(const JSON &other)
References JSON.
Topology * JSON::readTopology(string fileName)
Referenced by API::readTopology.
void JSON::writeTopology(Topology *topology, string fileName)
References Topology::getID.
Referenced by API::writeTopology.